owner: the-it-dept # Your GitHub organization or username, where this repository lives
repo: status.theitdept.au

user-agent: the-it-dept

sites:
  - name: Website
    url: https://theitdept.au

  - name: Portal
    url: https://portal.theitdept.au

  - name: Web Hosting Control Panel (web.theitdept.au)
    url: https://web.theitdept.au

  - name: web.oci.theitdept.au
    url: https://web.oci.theitdept.au
    expectedStatusCodes:
      - 200
      - 201
      - 404

  - name: cr1.syd1.theitdept.au
    check: "tcp-ping"
    url: 157.20.113.255
    port: 22



assignees:
  - nicko170

skipDeleteIssues: true

status-website:
  cname: status.theitdept.au
  logoUrl: https://raw.githubusercontent.com/the-it-dept/status.theitdept.au/master/assets/logo.png
  name: The IT Dept Pty Ltd
  introTitle: The IT Dept Pty Ltd Status
  introMessage: "Uptime monitor and status page for The IT Dept Pty Ltd."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "The IT Dept Pty Ltd"
  commitAuthorEmail: "status@theitdept.au"
